server:
  port: 8080  # 서버 포트 설정 (기본 포트는 8080)
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb;  # H2 데이터베이스 연결 (테스트용)
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximumPoolSize: 10  # HikariCP 최대 연결 수
  security:
    user:
      name: user
      password: password
  jwt:
    secret: "change-me-to-a-long-and-random-secret-key-of-at-least-64-characters-0123456789ABCDEFG"  # JWT 서명 키 (HS512 권장 64바이트 이상)
    expiration: 86400000  # 1일 (밀리초 단위)

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 자동 업데이트
    show-sql: true  # SQL 쿼리 출력

  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (http://localhost:8080/h2-console에서 사용 가능)
      path: /h2-console

  # Redis 설정
  data:
    redis:
      host: localhost  # Redis 서버 주소
      port: 6379       # Redis 포트 (기본값)
      timeout: 2000    # 연결 타임아웃 (밀리초)
      database: 0      # 사용할 데이터베이스 번호 (0-15)
      lettuce:
        pool:
          max-active: 8    # 최대 활성 연결 수
          max-idle: 8      # 최대 유휴 연결 수
          min-idle: 0      # 최소 유휴 연결 수
          max-wait: -1     # 연결 대기 시간 (-1은 무한 대기)
      # Redis 연결 실패 시 애플리케이션 시작 허용
      connect-timeout: 5000